name: tudat-bundle
channels:
  - conda-forge
  - tudat-team
dependencies:
  - eigen
  - boost-cpp
  - tudat-resources
  - sofa-cmake
  - nrlmsise-00
  - cspice-cmake
  - python=3.11
  - pybind11
  - pybind11-abi
  - numpy
  - pandas # for tudat.io
  - matplotlib # for tudat.plotting
  - pytest
