name: tudat-bundle
channels:
  - conda-forge
  - tudat-team
dependencies:
  - eigen=3.3.7
  - boost-cpp=1.72
  - tudat-resources
  - sofa-cmake
  - nrlmsise-00
  - cspice-cmake
  - python=3.8
  - pybind11
  - pybind11-abi
  - numpy
  - matplotlib # for tudat.plotting
  - basemap # for tudat.plotting
  - pytest
