name: tudat-bundle
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - astroquery
  - boost-cpp
  - cspice-cmake
  - eigen
  - matplotlib
  - nrlmsise-00
  - numpy
  - pandas
  - pybind11
  - pybind11-abi
  - pytest
  - python=3.11
  - sofa-cmake
  - tqdm
  - tudat-resources
  - backports
  - backports.tarfile
  - libblas[build=*accelerate]
  - scipy
  - numba
  - pygmo
  - sympy
  - h5py
  - scikit-learn
  - pathlib
  - mpi4py
